[package]
name = "frish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.22.0"
libc = "0.2"
log = "0.4.14"
env_logger = "0.9.0"
